/**
 * 稳定机器错误码（后端接口设计 §1.4 前缀约定 + §8 上传码表）；值不可改名，人话文案走 `error` 字段。
 * 分组常量合并进 ERROR_CODES，故键与取值同名，避免展开时互相覆盖。
 */

const AUTH_ERROR_CODES = {
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_BAD_CREDENTIALS: 'AUTH_BAD_CREDENTIALS',
  AUTH_DISABLED: 'AUTH_DISABLED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
} as const;

const COMMON_ERROR_CODES = {
  PARAM_INVALID: 'PARAM_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

const PROJECT_ERROR_CODES = {
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
} as const;

const PROTOTYPE_ERROR_CODES = {
  PROTO_NOT_FOUND: 'PROTO_NOT_FOUND',
  PROTO_SLUG_DUPLICATED: 'PROTO_SLUG_DUPLICATED',
  PROTO_CODE_INVALID: 'PROTO_CODE_INVALID',
  PROTO_CODE_IMMUTABLE: 'PROTO_CODE_IMMUTABLE',
  PROTO_NOT_ACCESSIBLE: 'PROTO_NOT_ACCESSIBLE',
  PROTO_ARCHIVED: 'PROTO_ARCHIVED',
  PROTO_POLICY_PASSWORD_REQUIRED: 'PROTO_POLICY_PASSWORD_REQUIRED',
  PROTO_POLICY_PASSWORD_INVALID: 'PROTO_POLICY_PASSWORD_INVALID',
} as const;

const RELEASE_ERROR_CODES = {
  RELEASE_NOT_FOUND: 'RELEASE_NOT_FOUND',
  RELEASE_NOT_READY: 'RELEASE_NOT_READY',
  RELEASE_IS_CURRENT: 'RELEASE_IS_CURRENT',
  RELEASE_VERSION_CONFLICT: 'RELEASE_VERSION_CONFLICT',
  UPLOAD_TASK_NOT_FOUND: 'UPLOAD_TASK_NOT_FOUND',
} as const;

const ACCESS_ERROR_CODES = {
  ACCESS_BAD_PASSWORD: 'ACCESS_BAD_PASSWORD',
  ACCESS_SOURCE_FORBIDDEN: 'ACCESS_SOURCE_FORBIDDEN',
} as const;

const SYSTEM_ERROR_CODES = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_OLD_PASSWORD_INVALID: 'USER_OLD_PASSWORD_INVALID',
  USER_PASSWORD_INVALID: 'USER_PASSWORD_INVALID',
  USER_RULE_LAST_SUPER_ADMIN: 'USER_RULE_LAST_SUPER_ADMIN',
  USER_RULE_SELF_DELETE: 'USER_RULE_SELF_DELETE',
  USER_RULE_SELF_ROLE_REVOKE: 'USER_RULE_SELF_ROLE_REVOKE',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_IN_USE: 'ROLE_IN_USE',
  ROLE_CODE_IMMUTABLE: 'ROLE_CODE_IMMUTABLE',
  ROLE_BUILT_IN_PROTECTED: 'ROLE_BUILT_IN_PROTECTED',
  MENU_NOT_FOUND: 'MENU_NOT_FOUND',
  MENU_HAS_CHILDREN: 'MENU_HAS_CHILDREN',
} as const;

/** 上传/发布错误码（后端接口设计 §8，13 条全量） */
export const UPLOAD_ERROR_CODES = {
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  UPLOAD_NOT_ZIP: 'UPLOAD_NOT_ZIP',
  UPLOAD_EMPTY: 'UPLOAD_EMPTY',
  UPLOAD_TOO_MANY_ENTRIES: 'UPLOAD_TOO_MANY_ENTRIES',
  UPLOAD_UNCOMPRESSED_TOO_LARGE: 'UPLOAD_UNCOMPRESSED_TOO_LARGE',
  UPLOAD_ENTRY_TOO_LARGE: 'UPLOAD_ENTRY_TOO_LARGE',
  UPLOAD_SUSPICIOUS_RATIO: 'UPLOAD_SUSPICIOUS_RATIO',
  UPLOAD_UNSAFE_PATH: 'UPLOAD_UNSAFE_PATH',
  UPLOAD_SYMLINK_NOT_ALLOWED: 'UPLOAD_SYMLINK_NOT_ALLOWED',
  UPLOAD_MISSING_ENTRY: 'UPLOAD_MISSING_ENTRY',
  UPLOAD_DUPLICATE_CONTENT: 'UPLOAD_DUPLICATE_CONTENT',
  UPLOAD_WORKER_FAILED: 'UPLOAD_WORKER_FAILED',
  UPLOAD_DISK_FULL: 'UPLOAD_DISK_FULL',
} as const;

export const ERROR_CODES = {
  ...AUTH_ERROR_CODES,
  ...COMMON_ERROR_CODES,
  ...PROJECT_ERROR_CODES,
  ...PROTOTYPE_ERROR_CODES,
  ...RELEASE_ERROR_CODES,
  ...ACCESS_ERROR_CODES,
  ...SYSTEM_ERROR_CODES,
  ...UPLOAD_ERROR_CODES,
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
export type UploadErrorCode = (typeof UPLOAD_ERROR_CODES)[keyof typeof UPLOAD_ERROR_CODES];

/**
 * 任务行 `proto_upload_task.error_code` 的取值域（§5.3 轮询响应里 `error.errorCode` 的取值）。
 *
 * §8 说"error_code 与 422 响应共用同一套码"并只列了 13 个上传码，而机制 §3.2 为"发布过程中
 * 原型/项目被删除"点名的是 `PROTO_NOT_FOUND`——归进 `UPLOAD_WORKER_FAILED`（"请重试"）会让用户
 * 照着建议去重传一个已经被删掉的原型。取值域取机制 §3.2（偏差见迭代实施计划 §9.2 DEV-18）。
 * 定义放在 shared：这是前后端共用的契约形状，服务端那层不该有它自己的一份真相。
 * 它只出现在任务状态里，**永远不会**作为 HTTP 响应的 `errorCode`（受理阶段的响应仍只有 §8 的 13 码）。
 */
export type UploadTaskErrorCode =
  | UploadErrorCode
  | typeof ERROR_CODES.PROTO_NOT_FOUND;

/** 取值域的唯一清单：库里那一列读回来时按它收敛，服务端与界面共用同一份真相。 */
export const UPLOAD_TASK_ERROR_CODES: readonly UploadTaskErrorCode[] = [
  ...Object.values(UPLOAD_ERROR_CODES),
  ERROR_CODES.PROTO_NOT_FOUND,
];

/** `proto_upload_task.error_code` 是 varchar(40) 且无 CHECK：越界值（人工改库/未来迁移）如实判出来。 */
export function isUploadTaskErrorCode(value: string): value is UploadTaskErrorCode {
  return (UPLOAD_TASK_ERROR_CODES as readonly string[]).includes(value);
}

/** 解压/改写阶段的非致命提示码（原型发布与访问机制 §2），出现在任务与版本的 warnings 里 */
export const UPLOAD_WARNING_CODES = {
  REWRITE_ABSOLUTE_PATH: 'REWRITE_ABSOLUTE_PATH',
  UNWRAP_SINGLE_TOP_DIR: 'UNWRAP_SINGLE_TOP_DIR',
  MULTI_ENTRY_CANDIDATES: 'MULTI_ENTRY_CANDIDATES',
  BASE_TAG_FOUND: 'BASE_TAG_FOUND',
  REWRITE_SKIPPED: 'REWRITE_SKIPPED',
  REWRITE_TOO_LARGE: 'REWRITE_TOO_LARGE',
} as const;

export type UploadWarningCode =
  (typeof UPLOAD_WARNING_CODES)[keyof typeof UPLOAD_WARNING_CODES];

/** 警告码取值域（同上：jsonb 读回来要按一份清单收敛，服务端与界面共用）。 */
export function isUploadWarningCode(value: string): value is UploadWarningCode {
  return (Object.values(UPLOAD_WARNING_CODES) as readonly string[]).includes(value);
}

/** §8 表格逐条对应；其它错误码的 HTTP 语义按 §1.4 的前缀规则判定，不在此建表 */
export const UPLOAD_ERROR_HTTP_STATUS: Record<UploadErrorCode, 200 | 413 | 422 | 500> = {
  UPLOAD_TOO_LARGE: 413,
  UPLOAD_NOT_ZIP: 422,
  UPLOAD_EMPTY: 422,
  UPLOAD_TOO_MANY_ENTRIES: 422,
  UPLOAD_UNCOMPRESSED_TOO_LARGE: 422,
  UPLOAD_ENTRY_TOO_LARGE: 422,
  UPLOAD_SUSPICIOUS_RATIO: 422,
  UPLOAD_UNSAFE_PATH: 422,
  UPLOAD_SYMLINK_NOT_ALLOWED: 422,
  UPLOAD_MISSING_ENTRY: 422,
  UPLOAD_DUPLICATE_CONTENT: 200,
  UPLOAD_WORKER_FAILED: 500,
  UPLOAD_DISK_FULL: 500,
};
