-- CreateTable
CREATE TABLE "sys_user" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "username" VARCHAR(50) NOT NULL,
    "password_hash" TEXT NOT NULL,
    "real_name" VARCHAR(50) NOT NULL,
    "email" VARCHAR(120),
    "phone" VARCHAR(20),
    "avatar" VARCHAR(500),
    "status" SMALLINT NOT NULL DEFAULT 1,
    "token_version" INTEGER NOT NULL DEFAULT 0,
    "force_password_change" BOOLEAN NOT NULL DEFAULT false,
    "auth_provider" VARCHAR(20) NOT NULL DEFAULT 'local',
    "last_login_at" TIMESTAMPTZ(6),
    "last_login_ip" INET,
    "remark" VARCHAR(200),
    "created_by" BIGINT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "sys_user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sys_role" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "code" VARCHAR(50) NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "data_scope" VARCHAR(20) NOT NULL DEFAULT 'member',
    "built_in" BOOLEAN NOT NULL DEFAULT false,
    "sort" INTEGER NOT NULL DEFAULT 0,
    "status" SMALLINT NOT NULL DEFAULT 1,
    "remark" VARCHAR(200),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "sys_role_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sys_user_role" (
    "user_id" BIGINT NOT NULL,
    "role_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sys_user_role_pkey" PRIMARY KEY ("user_id","role_id")
);

-- CreateTable
CREATE TABLE "sys_permission" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "code" VARCHAR(80) NOT NULL,
    "name" VARCHAR(80) NOT NULL,
    "module" VARCHAR(50) NOT NULL,
    "sort" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sys_permission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sys_role_permission" (
    "role_id" BIGINT NOT NULL,
    "permission_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sys_role_permission_pkey" PRIMARY KEY ("role_id","permission_id")
);

-- CreateTable
CREATE TABLE "sys_menu" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "pid" BIGINT,
    "type" VARCHAR(20) NOT NULL,
    "name" VARCHAR(80) NOT NULL,
    "title" VARCHAR(80) NOT NULL,
    "path" VARCHAR(200),
    "component" VARCHAR(200),
    "auth_code" VARCHAR(80),
    "icon" VARCHAR(80),
    "sort" INTEGER NOT NULL DEFAULT 0,
    "status" SMALLINT NOT NULL DEFAULT 1,
    "keep_alive" BOOLEAN NOT NULL DEFAULT false,
    "affix_tab" BOOLEAN NOT NULL DEFAULT false,
    "hide_in_menu" BOOLEAN NOT NULL DEFAULT false,
    "menu_visible_with_forbidden" BOOLEAN NOT NULL DEFAULT false,
    "authority" VARCHAR(200),
    "ignore_access" BOOLEAN NOT NULL DEFAULT false,
    "open_in_new_window" BOOLEAN NOT NULL DEFAULT false,
    "iframe_src" VARCHAR(500),
    "link_url" VARCHAR(500),
    "badge" VARCHAR(20),
    "badge_type" VARCHAR(20),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sys_menu_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sys_role_menu" (
    "role_id" BIGINT NOT NULL,
    "menu_id" BIGINT NOT NULL,

    CONSTRAINT "sys_role_menu_pkey" PRIMARY KEY ("role_id","menu_id")
);

-- CreateTable
CREATE TABLE "sys_login_log" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" BIGINT,
    "username" VARCHAR(50) NOT NULL,
    "login_type" VARCHAR(20) NOT NULL DEFAULT 'login',
    "success" BOOLEAN NOT NULL,
    "fail_reason" VARCHAR(120),
    "ip" INET,
    "user_agent" VARCHAR(500),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sys_login_log_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sys_oper_log" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" BIGINT,
    "username" VARCHAR(50),
    "module" VARCHAR(50) NOT NULL,
    "action" VARCHAR(50) NOT NULL,
    "resource_type" VARCHAR(50),
    "resource_id" VARCHAR(64),
    "resource_name" VARCHAR(200),
    "method" VARCHAR(10),
    "path" VARCHAR(300),
    "detail" JSONB,
    "ip" INET,
    "success" BOOLEAN NOT NULL DEFAULT true,
    "error_message" VARCHAR(500),
    "duration_ms" INTEGER,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sys_oper_log_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "proto_project" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(80) NOT NULL,
    "code" VARCHAR(63) NOT NULL,
    "description" VARCHAR(500),
    "archived_at" TIMESTAMPTZ(6),
    "created_by" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "proto_project_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "proto_prototype" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "project_id" BIGINT NOT NULL,
    "name" VARCHAR(80) NOT NULL,
    "code" VARCHAR(63) NOT NULL,
    "description" VARCHAR(500),
    "status" VARCHAR(20) NOT NULL DEFAULT 'draft',
    "access_mode" VARCHAR(20) NOT NULL DEFAULT 'public',
    "password_hash" TEXT,
    "policy_version" INTEGER NOT NULL DEFAULT 1,
    "current_release_id" BIGINT,
    "sort" INTEGER NOT NULL DEFAULT 0,
    "first_published_at" TIMESTAMPTZ(6),
    "published_at" TIMESTAMPTZ(6),
    "archived_at" TIMESTAMPTZ(6),
    "created_by" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "proto_prototype_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "proto_project_member" (
    "project_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "member_role" VARCHAR(20) NOT NULL DEFAULT 'viewer',
    "created_by" BIGINT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "proto_project_member_pkey" PRIMARY KEY ("project_id","user_id")
);

-- CreateTable
CREATE TABLE "proto_release" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "prototype_id" BIGINT NOT NULL,
    "version_no" INTEGER NOT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'ready',
    "storage_key" VARCHAR(300) NOT NULL,
    "entry_file" VARCHAR(200) NOT NULL DEFAULT 'index.html',
    "source_hash" VARCHAR(64) NOT NULL,
    "content_hash" VARCHAR(64) NOT NULL,
    "source_size" BIGINT NOT NULL,
    "file_count" INTEGER NOT NULL,
    "total_bytes" BIGINT NOT NULL,
    "manifest" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "note" VARCHAR(300),
    "created_by" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "proto_release_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "proto_release_event" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "prototype_id" BIGINT NOT NULL,
    "event_type" VARCHAR(20) NOT NULL,
    "from_release_id" BIGINT,
    "to_release_id" BIGINT,
    "operator_id" BIGINT NOT NULL,
    "reason" VARCHAR(300),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "proto_release_event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "proto_upload_task" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "prototype_id" BIGINT NOT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'pending',
    "progress" SMALLINT NOT NULL DEFAULT 0,
    "stage" VARCHAR(30),
    "source_name" VARCHAR(300) NOT NULL,
    "source_size" BIGINT NOT NULL,
    "temp_key" VARCHAR(300),
    "release_id" BIGINT,
    "error_code" VARCHAR(40),
    "error_message" VARCHAR(500),
    "warnings" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "created_by" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "started_at" TIMESTAMPTZ(6),
    "finished_at" TIMESTAMPTZ(6),

    CONSTRAINT "proto_upload_task_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "proto_access_log" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "prototype_id" BIGINT,
    "release_id" BIGINT,
    "route_key" VARCHAR(140) NOT NULL,
    "path" VARCHAR(500) NOT NULL,
    "result" VARCHAR(20) NOT NULL,
    "user_id" BIGINT,
    "ip" INET,
    "ua" VARCHAR(500),
    "browser" VARCHAR(40),
    "os" VARCHAR(40),
    "device" VARCHAR(20),
    "referer" VARCHAR(500),
    "is_bot" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "proto_access_log_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "idx_sys_user_role_role" ON "sys_user_role"("role_id");

-- CreateIndex
CREATE UNIQUE INDEX "uk_sys_permission_code" ON "sys_permission"("code");

-- CreateIndex
CREATE INDEX "idx_sys_role_permission_perm" ON "sys_role_permission"("permission_id");

-- CreateIndex
CREATE UNIQUE INDEX "uk_sys_menu_name" ON "sys_menu"("name");

-- CreateIndex
CREATE INDEX "idx_sys_menu_pid" ON "sys_menu"("pid", "sort");

-- CreateIndex
CREATE INDEX "idx_sys_role_menu_menu" ON "sys_role_menu"("menu_id");

-- CreateIndex
CREATE INDEX "idx_sys_login_log_user" ON "sys_login_log"("user_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "idx_sys_login_log_created" ON "sys_login_log"("created_at");

-- CreateIndex
CREATE INDEX "idx_sys_oper_log_resource" ON "sys_oper_log"("resource_type", "resource_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "idx_sys_oper_log_created" ON "sys_oper_log"("created_at");

-- CreateIndex
CREATE INDEX "idx_proto_project_archived" ON "proto_project"("archived_at");

-- CreateIndex
CREATE INDEX "idx_proto_prototype_project" ON "proto_prototype"("project_id", "sort");

-- CreateIndex
CREATE INDEX "idx_proto_project_member_user" ON "proto_project_member"("user_id");

-- CreateIndex
CREATE INDEX "idx_proto_release_prototype" ON "proto_release"("prototype_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "idx_proto_release_hash" ON "proto_release"("prototype_id", "source_hash");

-- CreateIndex
CREATE UNIQUE INDEX "uk_proto_release_version" ON "proto_release"("prototype_id", "version_no");

-- CreateIndex
CREATE INDEX "idx_proto_release_event_prototype" ON "proto_release_event"("prototype_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "idx_proto_upload_task_prototype" ON "proto_upload_task"("prototype_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "idx_proto_access_log_prototype" ON "proto_access_log"("prototype_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "idx_proto_access_log_created" ON "proto_access_log"("created_at");

-- AddForeignKey
ALTER TABLE "sys_user_role" ADD CONSTRAINT "fk_sys_user_role_user" FOREIGN KEY ("user_id") REFERENCES "sys_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "sys_user_role" ADD CONSTRAINT "fk_sys_user_role_role" FOREIGN KEY ("role_id") REFERENCES "sys_role"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "sys_role_permission" ADD CONSTRAINT "fk_sys_role_permission_role" FOREIGN KEY ("role_id") REFERENCES "sys_role"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "sys_role_permission" ADD CONSTRAINT "fk_sys_role_permission_permission" FOREIGN KEY ("permission_id") REFERENCES "sys_permission"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "sys_menu" ADD CONSTRAINT "fk_sys_menu_pid" FOREIGN KEY ("pid") REFERENCES "sys_menu"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "sys_role_menu" ADD CONSTRAINT "fk_sys_role_menu_role" FOREIGN KEY ("role_id") REFERENCES "sys_role"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "sys_role_menu" ADD CONSTRAINT "fk_sys_role_menu_menu" FOREIGN KEY ("menu_id") REFERENCES "sys_menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_project" ADD CONSTRAINT "fk_proto_project_created_by" FOREIGN KEY ("created_by") REFERENCES "sys_user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_prototype" ADD CONSTRAINT "fk_proto_prototype_project" FOREIGN KEY ("project_id") REFERENCES "proto_project"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_prototype" ADD CONSTRAINT "fk_proto_prototype_created_by" FOREIGN KEY ("created_by") REFERENCES "sys_user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_prototype" ADD CONSTRAINT "fk_proto_prototype_current_release" FOREIGN KEY ("current_release_id") REFERENCES "proto_release"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_project_member" ADD CONSTRAINT "fk_proto_project_member_project" FOREIGN KEY ("project_id") REFERENCES "proto_project"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_project_member" ADD CONSTRAINT "fk_proto_project_member_user" FOREIGN KEY ("user_id") REFERENCES "sys_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_release" ADD CONSTRAINT "fk_proto_release_prototype" FOREIGN KEY ("prototype_id") REFERENCES "proto_prototype"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_release" ADD CONSTRAINT "fk_proto_release_created_by" FOREIGN KEY ("created_by") REFERENCES "sys_user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_release_event" ADD CONSTRAINT "fk_proto_release_event_prototype" FOREIGN KEY ("prototype_id") REFERENCES "proto_prototype"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_release_event" ADD CONSTRAINT "fk_proto_release_event_operator" FOREIGN KEY ("operator_id") REFERENCES "sys_user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_upload_task" ADD CONSTRAINT "fk_proto_upload_task_prototype" FOREIGN KEY ("prototype_id") REFERENCES "proto_prototype"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proto_upload_task" ADD CONSTRAINT "fk_proto_upload_task_created_by" FOREIGN KEY ("created_by") REFERENCES "sys_user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- =============================================================================
-- NATIVE SQL (hand-added after `prisma migrate dev --create-only`)
-- Prisma schema 无法表达的对象，按 docs/数据库设计.md §4/§5 原样落库：
--   1) 条件唯一索引（软删除感知：WHERE deleted_at IS NULL / auth_code IS NOT NULL）
--   2) 表达式索引 lower(username)
--   3) 部分索引 WHERE status IN (...)
--   4) 文档 DDL 中的全部 CHECK 约束（含 ck_proto_prototype_pwd 与 code 格式校验）
-- CHECK 约束名沿用 PG 对文档内联 unnamed check 的自动命名 <table>_<column>_check，
-- 以保证与文档 DDL 的 pg_get_constraintdef 逐字可比。
-- =============================================================================

-- 4.1.1 sys_user：表达式条件唯一索引 + 条件索引（Prisma 不支持 lower() 与 WHERE）
CREATE UNIQUE INDEX "uk_sys_user_username" ON "sys_user" (lower("username")) WHERE "deleted_at" IS NULL;
CREATE INDEX "idx_sys_user_status" ON "sys_user" ("status") WHERE "deleted_at" IS NULL;

-- 4.1.2 sys_role：软删除感知的条件唯一索引；data_scope CHECK
CREATE UNIQUE INDEX "uk_sys_role_code" ON "sys_role" ("code") WHERE "deleted_at" IS NULL;
ALTER TABLE "sys_role" ADD CONSTRAINT "sys_role_data_scope_check" CHECK ("data_scope" IN ('all','member','own'));

-- 4.1.6 sys_menu：type CHECK；auth_code 条件唯一索引（非空才唯一）
ALTER TABLE "sys_menu" ADD CONSTRAINT "sys_menu_type_check" CHECK ("type" IN ('catalog','menu','button','embedded','link'));
CREATE UNIQUE INDEX "uk_sys_menu_auth_code" ON "sys_menu" ("auth_code") WHERE "auth_code" IS NOT NULL;

-- 4.1.8 sys_login_log：login_type CHECK
ALTER TABLE "sys_login_log" ADD CONSTRAINT "sys_login_log_login_type_check" CHECK ("login_type" IN ('login','logout','refresh_fail'));

-- 4.2.1 proto_project：code 格式 CHECK（访问路径第一段）；条件唯一/条件索引
ALTER TABLE "proto_project" ADD CONSTRAINT "proto_project_code_check" CHECK ("code" ~ '^[a-z0-9]+(-[a-z0-9]+)*$');
CREATE UNIQUE INDEX "uk_proto_project_code" ON "proto_project" ("code") WHERE "deleted_at" IS NULL;
CREATE INDEX "idx_proto_project_created_by" ON "proto_project" ("created_by") WHERE "deleted_at" IS NULL;

-- 4.2.2 proto_prototype：code 格式 CHECK（访问路径第二段）、status/access_mode CHECK、
-- ck_proto_prototype_pwd（password 档必须有密码散列）；访问热路径条件唯一索引；status 条件索引
ALTER TABLE "proto_prototype" ADD CONSTRAINT "proto_prototype_code_check" CHECK ("code" ~ '^[a-z0-9]+(-[a-z0-9]+)*$');
ALTER TABLE "proto_prototype" ADD CONSTRAINT "proto_prototype_status_check" CHECK ("status" IN ('draft','published','archived'));
ALTER TABLE "proto_prototype" ADD CONSTRAINT "proto_prototype_access_mode_check" CHECK ("access_mode" IN ('public','password','member'));
ALTER TABLE "proto_prototype" ADD CONSTRAINT "ck_proto_prototype_pwd" CHECK ("access_mode" <> 'password' OR "password_hash" IS NOT NULL);
CREATE UNIQUE INDEX "uk_proto_prototype_code" ON "proto_prototype" ("project_id", "code") WHERE "deleted_at" IS NULL;
CREATE INDEX "idx_proto_prototype_status" ON "proto_prototype" ("status") WHERE "deleted_at" IS NULL;

-- 4.2.3 proto_project_member：member_role CHECK
ALTER TABLE "proto_project_member" ADD CONSTRAINT "proto_project_member_member_role_check" CHECK ("member_role" IN ('owner','editor','viewer'));

-- 4.2.4 proto_release：status CHECK（注意：uk_proto_release_version 保持无条件——
-- 它是并发发布抢 version_no 的最终防线，见文档 §5，勿加 deleted_at 条件）
ALTER TABLE "proto_release" ADD CONSTRAINT "proto_release_status_check" CHECK ("status" IN ('ready','broken','deleted'));

-- 4.2.5 proto_release_event：event_type CHECK
ALTER TABLE "proto_release_event" ADD CONSTRAINT "proto_release_event_event_type_check" CHECK ("event_type" IN ('publish','rollback','unpublish','republish','delete_version'));

-- 4.2.6 proto_upload_task：status/progress CHECK；Worker 拉取用部分索引
ALTER TABLE "proto_upload_task" ADD CONSTRAINT "proto_upload_task_status_check" CHECK ("status" IN ('pending','processing','success','failed','canceled'));
ALTER TABLE "proto_upload_task" ADD CONSTRAINT "proto_upload_task_progress_check" CHECK ("progress" BETWEEN 0 AND 100);
CREATE INDEX "idx_proto_upload_task_todo" ON "proto_upload_task" ("status", "created_at") WHERE "status" IN ('pending','processing');

-- 4.2.7 proto_access_log：result CHECK（prototype_id/release_id/user_id 刻意无外键，见文档 §2）
ALTER TABLE "proto_access_log" ADD CONSTRAINT "proto_access_log_result_check" CHECK ("result" IN ('ok','denied_401','denied_403','not_found'));
